name: Publish release artifacts

env:
   module_id: scoresaber
   qmodName: ScoreSaber

on:
   push:
      tags:
         - 'v*.*.*-bs-*.*.*'

jobs:
   publish:
      runs-on: ubuntu-latest

      steps:
         - name: Get Mod and game version from tag name
           id: modversion
           run: |
              TEMP=$(echo "$GITHUB_REF_NAME" | grep -Po "(?<=v)\d+.\d+.\d+")
              echo "VERSION=$TEMP" >> $GITHUB_ENV
              TEMP=$(echo "$GITHUB_REF_NAME" | grep -Po "(?<=bs-)[.\d_]*")
              echo "BS_VERSION=$TEMP" >> $GITHUB_ENV

         - uses: actions/checkout@v3
           name: Checkout
           with:
              submodules: true
              lfs: true

         - uses: seanmiddleditch/gha-setup-ninja@v3

         - name: Create ndkpath.txt
           run: |
              echo "$ANDROID_NDK_LATEST_HOME" > ${GITHUB_WORKSPACE}/ndkpath.txt
              cat ${GITHUB_WORKSPACE}/ndkpath.txt
         - name: Get QPM
           if: steps.cache-qpm.outputs.cache-hit != 'true'
           uses: dawidd6/action-download-artifact@v2
           with:
              github_token: ${{secrets.GITHUB_TOKEN}}
              workflow: cargo-build.yml
              name: linux-qpm-rust
              path: QPM
              repo: RedBrumbler/QuestPackageManager-Rust

         - name: QPM Collapse
           run: |
              chmod +x ./QPM/qpm-rust
              ./QPM/qpm-rust collapse
         - name: QPM Dependencies Cache
           id: cache-qpm-deps
           uses: actions/cache@v3
           env:
              cache-name: cache-qpm-deps
           with:
              path: /home/runner/.local/share/QPM-Rust/cache
              key: ${{ runner.os }}-build-${{ env.BS_VERSION }}-${{ env.cache-name }}-${{ hashFiles('qpm.json') }}
              restore-keys: |
                 ${{ runner.os }}-build-${{ env.BS_VERSION }}-${{ env.cache-name }}-
                 ${{ runner.os }}-build-
                 ${{ runner.os }}-
         - name: QPM Restore
           run: |
              chmod +x ./QPM/qpm-rust
              ./QPM/qpm-rust restore
         - name: QPM Legacy fix
           run: |
              chmod +x ./QPM/qpm-rust
              ./QPM/qpm-rust cache legacy-fix
         - name: List Post Restore
           run: |
              echo includes:
              ls -la ${GITHUB_WORKSPACE}/extern/includes
              echo libs:
              ls -la ${GITHUB_WORKSPACE}/extern/libs
              echo cache:
              ls -la $HOME/.local/share/QPM-Rust/cache

         - name: QPM Edit Version
           run: |
              ./QPM/qpm-rust package edit --version "${{ env.VERSION }}"

         - name: Build
           run: |
              cd ${GITHUB_WORKSPACE}
              pwsh -Command ./build.ps1
              ./QPM/qpm-rust qmod build

         - name: Create Qmod
           run: |
              pwsh -Command ./createqmod.ps1 ${{env.qmodName}}

         - name: Get Library Name
           id: libname
           run: |
              cd ./build/
              pattern="lib${module_id}*.so"
              files=( $pattern )
              echo "LIBNAME=${files[0]}" >> $GITHUB_ENV

         - name: Release
           uses: softprops/action-gh-release@v1
           if: startsWith(github.ref, 'refs/tags/')
           with:
              files: |
                 ./${{ env.qmodName }}.qmod
                 ./build/${{ env.LIBNAME }}
